### ISSUE TITLE
Planet X should be unknown

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs-basics#11]
Planet X should behave the same as MAS.

Currently, selecting Planet X looks like this:
![image](https://user-images.githubusercontent.com/8419308/46590415-42c2a300-ca70-11e8-9e0f-b6688b3ab85a.png)

Instead, the HSlider should disappear, and and be replaced with the string, "What is the value of gravity?" All of the logic switching between Planet X and the other benchmarks should also match MAS.

**Comment by Denz1994** [comment]
Similar logic was added to GravityAccordionBox.js from GravityAndDampingControlNode.js. Because we aren't using a NumberControl, explicit visibility toggling logic needed to be implemented, along with some alignment adjustments.

Please review the above changes @arouinfar especially, when toggling from custom to Planet X.

**Comment by arouinfar** [comment]
The behavior now matches MAS. Thanks @Denz1994!
