### ISSUE TITLE
Stretch Screen Design Notes

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/masses-and-springs-basics#38]
When testing for https://github.com/phetsims/QA/issues/220 there are some small design notes I have that might improve with student understanding. The first one is the lack of a timer on the stretch screen. It is weird to me that all other masses and springs screens have a timer but not this screen, however this does not take away much of the functionality or content. The other improvement suggestion is to include something about the damping of the springs on the stretch screen. The stretch screen and bounce screen are almost identical and to someone who is just starting to learn about springs for the first time it might be confusing why one mass spring system will stop oscillating after some time while an identical system with no other indicators will continue to oscillate indefinitely. Adding in a damping slider like the one on the energy screen of masses and springs, or a damping value indicator like on the vectors screen of masses and springs could aid in student understanding of why one system will slow and the other will not.

**Comment by Denz1994** [comment]
This is a design discussion so I'm assigning @arouinfar to offer input.

**Comment by arouinfar** [comment]
The target audience of this sim is students in upper elementary/middle school. The Stretch screen is designed to facilitate learning goals related to Hooke's Law, while the Bounce screen focuses more on period/oscillations. For Hooke's Law, it's important for the oscillations to quickly die off so that students spend more time focusing on how far the spring stretches at equilibrium. To achieve this goal, we chose to give the spring on the Stretch screen a very large damping. The color of the springs is also a subtle cue that these springs are different from the ones on later screens.

>The first one is the lack of a timer on the stretch screen. It is weird to me that all other masses and springs screens have a timer but not this screen, however this does not take away much of the functionality or content. 

While I recognize that it could be a little odd that the timer is not on the first screen, this was an intentional choice. Given the large damping on the Stretch screen, the timer does not provide any meaningful data.  The timer being a "new" feature on the Bounce screen may also lead students to play with it, which is important for the learning goals around period.

> The other improvement suggestion is to include something about the damping of the springs on the stretch screen. 

Damping is a rather advanced topic, and is beyond the scope of the learning goals for the Basics version of this sim. Damping can be explored in the full version of Masses and Springs.

Thank you for your observations @JRomero0613. Please continue to open design issues while you test sims. While we won't be making any changes in this particular case, it is helpful to hear this sort of feedback. I will be sure to note the implicit damping behavior in the Teacher Tips document.
