### ISSUE TITLE
Period tracer line inhibits grabbing mass slider

### ISSUE THREAD

**Issue by rea-laura** [phetsims/masses-and-springs-basics#42]
<b>Test Device</b>

Personal Laptop

<b>Operating System</b>

Windows 10 Version 10.0.17134 Build 17134

<b>Browser</b>

Chrome 70.0.3538.102
Firefox Quantum 63.0.3

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/220:
When period tracer line covers mass slider, the slider is harder to grab. Also found in the published Masses and Springs.

<b>Steps to Reproduce</b>

1) open sim: https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.11/phet/masses-and-springs-basics_en_phet.html
2) go to "Lab" from the home screen.
3) attach the orange adjustable weight to the spring
4) slide weight mass to max (300g)
5) make the spring bounce
6) using the spring strength slider, adjust the strength mid-bounce to "slingshot" the spring so its bounce height covers the full screen
7) from the right hand toolbar, select "Period Trace"
8) the period trace will draw a line over the mass slider, making it hard to interact with the slider while the lines are on top of it.
9) if the tracer line does not go over the mass slider, resizing the window can make this happen

<b>Visuals</b>

![image](https://user-images.githubusercontent.com/44005544/48650939-ccda2180-e9b5-11e8-8847-cee5422de925.png)

**Comment by arouinfar** [comment]
Nice catch @rea-laura! 

When the Period Trace is layered over the slider thumb, the thumb is no longer pickable (cursor is an arrow, not a hand), even when trying to click between the lines.

The mass's oscillation has to be pretty wild for the Period Trace to cover the Mass panel, and at least part of the trace is likely off-screen in such a case. Here, the Period Trace is not all that pedagogically useful. 

I would recommend that we layer the Period Trace behind the Mass panel. Under normal usage, where the period trace is pedagogically useful, the Period Trace would never be occluded by the Mass panel, anyway, since this is max compression:
![image](https://user-images.githubusercontent.com/8419308/48651608-e761ca00-e9b8-11e8-98ce-4b4a24e11464.png)

**Comment by Denz1994** [comment]
I have pushed a fix to master that should have corrected this behavior in both MASB and MAS. I will push a new dev version for verification, but this change should be included in the next maintenance release of MAS.

**Comment by Denz1994** [comment]
Can you test if this change is acceptable in this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.12/phet/masses-and-springs-basics_all_phet.html) @KatieWoe? If all looks good please reassign to me.

**Comment by KatieWoe** [comment]
Looks good

**Comment by Denz1994** [comment]
This fix should also be applied to MAS on next maintenance release.

**Comment by Nancy-Salpepi** [comment]
This looks good in 1.1.0-dev.1. Closing.
