### ISSUE TITLE
Add a Gravity Accordion Box to Lab Screen

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs-basics#6]
During the design meeting on 10/05/18 @kathy-phet and @arouinfar decided on adding an accordion box that contains the options for gravity. I have added some preliminary code for this accordion box. @arouinfar will provide mock-ups.

This issue is opened to provide review comments for the gravity accordion box.

**Comment by Denz1994** [comment]
Adding dev version [1.0.0-dev.2](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.2/phet/masses-and-springs-basics_en_phet.html) here for review.

**Comment by arouinfar** [comment]
Looking pretty good @Denz1994. I have a few requests:
- [ ] Left-align "Gravity" instead of centering it (too much negative space)
- [ ] The HSlider and comboBox could both be a bit wider

Here's a mockup for reference:
![image](https://user-images.githubusercontent.com/8419308/46564298-ac517e80-c8c3-11e8-9049-cc9999ee6da3.png)

**Comment by Denz1994** [comment]
The above changes have been made to the GravityAccordionBox. Please review @arouinfar in master.

**Comment by arouinfar** [comment]
Looks good! Thanks @Denz1994.

**Comment by arouinfar** [comment]
One last request -- @Denz1994 can you make the accordion box closed by default?

**Comment by Denz1994** [comment]
The accordion box has been set to non-expanded by default. Leaving to @arouinfar to close.

**Comment by arouinfar** [comment]
👍
