### ISSUE TITLE
Pointer Area Overlap of mass adjuster

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs-basics#60]
For https://github.com/phetsims/QA/issues/281
This overlap of the mass adjustment slider and button can lead to the wrong object being selected, but it hasn't caused many problems unless I was trying.
![71ac1050-83c3-42d9-b8d4-7cb4e9bd92a4](https://user-images.githubusercontent.com/41024075/52670713-7f971e80-2ed6-11e9-91bf-8c450a6be378.png)

**Comment by arouinfar** [comment]
@Denz1994 while you're adjusting the x-dilation on the mass slider thumb, you may also want to reduce the y-dilation on the gravity slider thumb so it doesn't overlap the combobox.

![image](https://user-images.githubusercontent.com/8419308/52671259-cd605680-2ed7-11e9-836a-327d9405911e.png)

**Comment by Denz1994** [comment]
`touchAreaXDilation` and `touchAreaYDilation` were adjusted for the gravity and mass value sliders. I will push another RC for verification/review.

**Comment by Denz1994** [comment]
These changes should be cherry-picked into master at the next maintenance release of MAS

**Comment by Denz1994** [comment]
Changes cherry-picked into master. Also, some changes to the `touchAreaXDialtion` were committed to both relevant branches. This is ready for verification in next RC.

**Comment by KatieWoe** [comment]
Still occurs a bit in both cases, but seems better.  Will eave up to @arouinfar to see if she finds it acceptable.  MASB 1.0.0-rc.3

**Comment by arouinfar** [comment]
Comparnig rc.3 (left) to rc.2 (right), the pointer area overlaps have reduced, and look reasonable to me. I wouldn't want to make the x-dilation on the mass slider thumb any smaller because I think the slider would become harder to use.
<img src="https://user-images.githubusercontent.com/8419308/54444938-64a01000-4709-11e9-9a1e-f5ac4acbdb99.png" width=250> <img src="https://user-images.githubusercontent.com/8419308/54445028-944f1800-4709-11e9-8a21-18b66618a912.png" width=250>

<img src="https://user-images.githubusercontent.com/8419308/54444955-6cf84b00-4709-11e9-865c-cf4326ae8618.png" width=250> <img src="https://user-images.githubusercontent.com/8419308/54445089-b3e64080-4709-11e9-9e97-4097039a7103.png" width=250>
