### ISSUE TITLE
Period Trace can change size when paused with LoL

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs-basics#65]
For https://github.com/phetsims/QA/issues/296
When the period trace is in the middle of drawing its second piece, pause the sim with the LoL harness.  When unpaused the leg will be shorter than it should be.  It doesn't seem to work when the sim is in the slowed down speed, and so timing this can be tricky.  Takes several tries in the bellow gif.  It resolves itself upon the next pass of the spring.  I'm inclined to believe that this is rather minor, but I'll leave that up to @Denz1994 and @ariel-phet to decide.
![lolattemptsperiod](https://user-images.githubusercontent.com/41024075/54460810-3f72c800-4730-11e9-9639-235f676b48ea.gif)

**Comment by arouinfar** [comment]
@KatieWoe nice catch. This seems like an edge case to me, and would agree it's pretty minor (but keep reporting this kind of stuff!). As you mentioned, it takes several tries to pause the harness in the right spot, and the period trace will correctly draw on the next pass. 

@Denz1994 if you see some obvious reason why this bug may be occurring,  feel free to address. Otherwise, please close.

**Comment by Denz1994** [comment]
> If you see some obvious reason why this bug may be occurring, feel free to address. Otherwise, please close.

Not exactly obvious, but my hunch is that the step calls are out of sync at some point when playing and pausing the wrapper and not the sim. This may be related to https://github.com/phetsims/joist/issues/515#issuecomment-422432002.

I'll close this issue because the physics of the sim isn't being broken.
